version: "3.8"

services:
  php:
    image: php:8.2-apache
    build: . 
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./composer.json:/var/www/html/composer.json
      - ./vendor:/var/www/html/vendor
      - ./virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    # environment:
      # APACHE_DOCUMENT_ROOT: /var/www/html
    # depends_on:
      # - mysql
      # - postgres

  mysql:
    image: mysql:8.0.31
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: safebase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./grant_privileges.sql:/docker-entrypoint-initdb.d/grant_privileges.sql
      # - ./safebase.sql:/docker-entrypoint-initdb.d/safebase.sql
      # - ./sql_dumps:/docker-entrypoint-initdb.d  # Dossier pour tes dumps SQL

  # postgres:
  # image: postgres:16
  # ports:
  # - "5433:5432"
  # environment:
  # POSTGRES_USER: user
  # POSTGRES_PASSWORD: userpassword
  # POSTGRES_DB: my_database
  # volumes:
  # - postgres_data:/var/lib/postgresql/data
  # - ./pg_dumps:/docker-entrypoint-initdb.d  # Dossier pour tes dumps PostgreSQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      UPLOAD_LIMIT: 20M
    ports:
      - "8081:80"
    depends_on:
      - mysql

  # pgadmin:
  # image: dpage/pgadmin4
  # container_name: pgadmin
  # environment:
  # PGADMIN_DEFAULT_EMAIL: admin@admin.com
  # ports:
  # - "8082:80"
  # depends_on:
  # - postgres

volumes:
  mysql_data:
  postgres_data:
